version: '3'

services:
  web:
    build:
      context: ./php-docker
    container_name: dev-php
    volumes:
      - ../:/app
    working_dir: /app/public
    tty: true
    ports:
      - ${APP_HTTP_PORT}:1111
    command: php -S 0.0.0.0:1111 /app/public/index.php
